name: Build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: windows-latest
    steps:      
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      - name: Restore Packages
        run: nuget restore HeistProject.sln
      - name: Build Solution
        run: |
          msbuild.exe HeistProject.sln /p:platform="x64" /p:configuration="Release"
      - name: Copy HeistProject Data Files
        run: Copy 'HeistProjectFiles/' 'bin/x64/Release/HeistProject' -recurse
        shell: powershell
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: 'bin/x64/Release'
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%s)"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.timestamp.outputs.timestamp }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/x64/Release/release.zip
          asset_name: release.zip
          asset_content_type: application/zip
